#!/bin/bash

VB_DEFAULT_MEM=512
DRIVER_DEFINITION="--driver virtualbox --virtualbox-memory=$VB_DEFAULT_MEM"
ES_MAXMEM=256m
SWARM_NODES=4
ES_NODES=5
SWARM_IMAGE=swarm:1.0.0
ELASTICSEARCH_IMAGE=elasticsearch-srv
CONSUL_PORT_UDP=8600
CONSUL_PORT_TCP=8653
CONSUL_PORT=$CONSUL_PORT_TCP
SRV_PROTOCOL=tcp
DISCOVERY_LOGLEVEL=TRACE
